name: 'Terraform Destroy for AKS'

on:
  workflow_dispatch:   # permite rodar manualmente pelo GitHub Actions

permissions:
  contents: read

jobs:
  terraform_destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init
        env:
          ARM_BACKEND_RESOURCE_GROUP_NAME: ${{ secrets.ARM_BACKEND_RG }}
          ARM_BACKEND_STORAGE_ACCOUNT_NAME: ${{ secrets.ARM_BACKEND_STORAGE_ACCOUNT }}
          ARM_BACKEND_CONTAINER_NAME: ${{ secrets.ARM_BACKEND_CONTAINER }}
          ARM_BACKEND_KEY: "aks-cluster/prod/terraform.tfstate"

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
